baseURL = "https://diacoro926.github.io/ohana-gats-web/"
title = "Ohana"
theme = "beautifulhugo"

defaultContentLanguage = "es"
defaultContentLanguageInSubdir = true
enableEmoji = true

pygmentsStyle = "trac"
pygmentsUseClasses = true
pygmentsCodeFences = true
pygmentsCodefencesGuessSyntax = true

[Params]
  subtitle = "Asociación de gatos Ohana"
  logo = "img/Ohana.png"
  favicon = "img/OhanaIco.ico"
  dateFormat = "January 2, 2006"
  commit = false
  rss = false
  comments = true
  readingTime = true
  wordCount = true
  useHLJS = true
  socialShare = true
  delayDisqus = true
  showRelatedPosts = true
  since = 2024
  hideAuthor = true

[Params.author]
  instagram = "adopta.gats.prat/"
  tiktok = "adopta.gats.prat"
  Teaming = "adoptagatsprat/"
  email = "Ohanagatsprat@gmail.com"

# --------------------
# Languages
# --------------------

[languages]

[languages.es]
  weight = 1
  title = "Ohana"
  languageName = "Español"

  [[languages.es.menu.main]]
    name = "Inicio"
    url = ""
    weight = 1

  [[languages.es.menu.main]]
    name = "Adoptame"
    url = "cats/"
    weight = 2

  [[languages.es.menu.main]]
    name = "Acerca de"
    url = "page/about/"
    weight = 3

  [[languages.es.menu.main]]
    name = "Ayudanos"
    url = "page/helpus/"
    weight = 4

  [[languages.es.menu.main]]
    name = "Contacto"
    url = "page/contact/"
    weight = 5


[languages.ca]
  weight = 2
  title = "Ohana"
  languageName = "Català"

  [[languages.ca.menu.main]]
    name = "Inici"
    url = ""
    weight = 1

  [[languages.ca.menu.main]]
    name = "Adopta’m"
    url = "cats/"
    weight = 2

  [[languages.ca.menu.main]]
    name = "Sobre nosaltres"
    url = "page/about/"
    weight = 3

  [[languages.ca.menu.main]]
    name = "Ajuda’ns"
    url = "page/helpus/"
    weight = 4

  [[languages.ca.menu.main]]
    name = "Contacte"
    url = "page/contact/"
    weight = 5


[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
